version: '3.14'
services:
  inventory-command:
    build:
      context: ./
      dockerfile: Command.Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_DB_URI=mongodb://rodri:rodri007@mongo-inventory:27017/inventory?authSource=admin
      - RABBIT_MQ_URI=amqp://rabbitmq-inventory:5672
    links:
      - mongo-inventory
      - rabbitmq-inventory
    volumes:
      - command-data:/command/app/data
  inventory-query:
    build:
      context: ./
      dockerfile: Query.Dockerfile
    ports:
      - 3001:3001
    environment:
      - RABBIT_MQ_URI=amqp://rabbitmq-inventory:5672
      - MYSQL_DB_USER=root
      - MYSQL_DB_PASSWORD=rodri007
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_HOST=mysql-inventory
      - MYSQL_DB_DATABASE=inventory
    links:
      - mysql-inventory
      - rabbitmq-inventory
    volumes:
      - query-data:/query/app/data
  inventory-socket:
    build:
      context: ./
      dockerfile: Socket.Dockerfile
    ports:
      - 3003:3003
      - 3004:3004
    environment:
      - RABBIT_MQ_URI=amqp://rabbitmq-inventory:5672
    links:
      - rabbitmq-inventory
    volumes:
      - socket-data:/query/app/data
  mongo-inventory:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rodri
      - MONGO_INITDB_ROOT_PASSWORD=rodri007
      - MONGO_INITDB_DATABASE=inventory
    volumes:
      - mongo-data:/data/db
  mysql-inventory:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rodri007
      - MYSQL_DATABASE=inventory
    volumes:
      - mysql-data:/var/lib/mysql
  rabbitmq-inventory:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
volumes:
  command-data:
  query-data:
  socket-data:
  mongo-data:
  mysql-data:
  rabbitmq-data:
